#!/usr/bin/env bash

set -u

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
MODULES_DIR="$SCRIPT_DIR/modules"

echo "Ensure HomeBrew installed"
if [[ -x /opt/homebrew/bin/brew ]]; then
  echo "HomeBrew already installed"
else
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "Load HomeBrew into current shell"
eval "$(/opt/homebrew/bin/brew shellenv zsh)"

echo "Linking .zprofile"
ln -sf $SCRIPT_DIR/.zprofile "$HOME/.zprofile"


echo "Installing modules/git"
brew bundle install --file="$MODULES_DIR/git/Brewfile"
"$MODULES_DIR/git/setup"
