#!/usr/bin/env bash

set -u

SCRIPT_DIR="$(dirname -- "${BASH_SOURCE[0]}")"

MODULES=(
  apps
  bashdev
  zsh
  git
  ssh
)

for module in "${MODULES[@]}"; do
  if ! "$SCRIPT_DIR/../$module/setup"; then
    exit 1
  fi
done
