#!/usr/bin/env bash

set -u

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
PROJECT_ROOT="$(cd -- "$SCRIPT_DIR/../.." &>/dev/null && pwd)"

cd "$PROJECT_ROOT" || exit 1

source lib/ensure_homebrew.sh
source lib/module.sh

MODULE_NAME=$(basename -- "$SCRIPT_DIR")
MODULE_DIR="$PROJECT_ROOT/modules/$MODULE_NAME"

LINKS=(
  "$MODULE_DIR/config:$HOME/.ssh/config"
  "$MODULE_DIR/config.d/all_hosts:$HOME/.ssh/config.d/all_hosts"
)

ensure_ssh_dir() {
  mkdir -p "$HOME/.ssh/config.d" \
    && chmod 0700 "$HOME/.ssh" \
    && chmod 0700 "$HOME/.ssh/config.d"
}

"$PROJECT_ROOT/modules/1password/setup" \
  && ensure_ssh_dir \
  && create_links "$MODULE_NAME" "${LINKS[@]}"
